### ISSUE TITLE
Openbanking Scopes From the DCR should reflect in the client. The client has been vetted by the OBIE which is the reason for ensuring trust

### ISSUE THREAD

**Issue by HemantKMehta** [JanssenProject/jans-setup#32]
During DCR testing the client gets created but only with one scope (openid) other three passed scopes (accounts payments, fundsconfirmations) were not added into the client scope in database. This is as they are not the so we need to make all four scopes as default.

**Comment by HemantKMehta** [comment]
Fixed it here in commit ef85305  
https://github.com/JanssenProject/jans-setup/commit/ef8530553ab21e8c4a47da3b3203477080cae233

**Comment by nynymike** [comment]
Please back out this change. Scopes should be mapped during DCR according to the software statement.

**Comment by HemantKMehta** [comment]
Now the scopes.json is back to the previous state with commit cd5ba13.
